

export const destinations = [
            {
              id: 1,
              name: 'Dubai',
              description: 'A city in the UAE known for luxury shopping, and a lively nightlife.',
              continent: 'Asia',
              climate: 'Hot desert',
              bestTimeToVisit: 'November to March',
              language: 'Arabic',
              currency: 'UAE dirham',
              image: '/pictures/asia/dubai.jpg'
            },
            {
              id: 2,
              name: 'Hong Kong',
              description: 'A city in China known for its skyline, shopping, and food scene.',
              continent: 'Asia',
              climate: 'Humid subtropical',
              bestTimeToVisit: 'October to December',
              language: 'Cantonese',
              currency: 'Hong Kong dollar',
              image: '/pictures/asia/hongkong.jpg'
            },
            {
              id: 3,
              name: 'Tokyo',
              description: 'The bustling capital of Japan.',
              continent: 'Asia',
              climate: 'Humid subtropical',
              bestTimeToVisit: 'March to May, or September to November',
              language: 'Japanese',
              currency: 'Japanese yen',
              image: '/pictures/asia/japan.jpg'
            },
            {
              id: 4,
              name: 'Kuala Lumpur',
              description: 'The capital and largest city of Malaysia.',
              continent: 'Asia',
              climate: 'Tropical rainforest',
              bestTimeToVisit: 'May to July',
              language: 'Malay',
              currency: 'Malaysian ringgit',
              image: '/pictures/asia/malaysia.jpg'
            },
            {
              id: 5,
              name: 'Maldives',
              description: 'A tropical paradise in the Indian Ocean known for its beaches, coral reefs, and luxury resorts.',
              continent: 'Asia',
              climate: 'Tropical',
              bestTimeToVisit: 'November to April',
              language: 'Dhivehi',
              currency: 'Maldivian rufiyaa',
              image: '/pictures/asia/maldives.jpg'
            },
            {
              id: 6,
              name: 'Doha',
              description: 'The capital city of Qatar, known for its futuristic architecture and luxury shopping.',
              continent: 'Asia',
              climate: 'Hot desert',
              bestTimeToVisit: 'November to April',
              language: 'Arabic',
              currency: 'Qatari riyal',
              image: '/pictures/asia/qatar.jpg'
            },
            {
              id: 7,
              name: 'Singapore',
              description: 'A bustling city-state known for its cleanliness, shopping, and food scene.',
              continent: 'Asia',
              climate: 'Tropical rainforest',
              bestTimeToVisit: 'February to April',
              language: 'English, Malay, Mandarin, Tamil',
              currency: 'Singapore dollar',
              image: '/pictures/asia/singapore.jpg'
            },
            {
              id: 8,
              name: 'Bangkok',
              description: 'The capital and largest city of Thailand, known for its temples, street food, and nightlife.',
              continent: 'Asia',
              climate: 'Tropical savanna',
              bestTimeToVisit: 'November to February',
              language: 'Thai',
              currency: 'Thai baht',
              image: '/pictures/asia/thailand.jpg'
            },
            {
              id: 9,
              name: 'Algiers',
              description: 'The capital and largest city of Algeria.',
              continent: 'Africa',
              climate: 'Mediterranean',
              bestTimeToVisit: 'April to June, or September to November',
              language: 'Arabic',
              currency: 'Algerian dinar',
              image: '/pictures/africa/algeria.jpg'
            },
            {
              id: 10,
              name: 'Cairo',
              description: 'The capital and largest city of Egypt, known for its ancient pyramids and the Sphinx.',
              continent: 'Africa',
              climate: 'Hot desert',
              bestTimeToVisit: 'November to March',
              language: 'Arabic',
              currency: 'Egyptian pound',
              image: '/pictures/africa/egypt.jpg'
            },
            {
              id: 11,
              name: 'Addis Ababa',
              description: 'The capital and largest city of Ethiopia.',
              continent: 'Africa',
              climate: 'Subtropical highland',
              bestTimeToVisit: 'October to February',
              language: 'Amharic',
              currency: 'Ethiopian birr',
              image: '/pictures/africa/ethiopia.jpg'
            },
            {
              id: 12,
              name: 'Nairobi',
              description: 'The capital and largest city of Kenya, known for its wildlife and national parks.',
              continent: 'Africa',
              climate: 'Tropical',
              bestTimeToVisit: 'January to February, or June to October',
              language: 'Swahili, English',
              currency: 'Kenyan shilling',
              image: '/pictures/africa/kenya.jpg'
            },
            {
              id: 13,
              name: 'Antananarivo',
              description: 'The capital and largest city of Madagascar.',
              continent: 'Africa',
              climate: 'Tropical',
              bestTimeToVisit: 'April to December',
              language: 'Malagasy, French',
              currency: 'Malagasy ariary',
              image: '/pictures/africa/madagascar.jpg'
            },
            {
              id: 14,
              name: 'Marrakesh',
              description: 'A city in Morocco known for its souks, palaces, and gardens.',
              continent: 'Africa',
              climate: 'Semi-arid',
              bestTimeToVisit: 'March to May, or September to November',
              language: 'Arabic',
              currency: 'Moroccan dirham',
              image: '/pictures/africa/morocco.jpg'
            },
            {
              id: 15,
              name: 'Cape Town',
              description: 'The southernmost city on the African continent.',
              continent: 'Africa',
              climate: 'Mediterranean',
              bestTimeToVisit: 'September to November, or February to April',
              language: 'English',
              currency: 'South African rand',
              image: '/pictures/africa/capetown.jpg'
            },
            {
              id: 16,
              name: 'Dar es Salaam',
              description: 'The largest city in Tanzania, known for its beaches and music scene.',
              continent: 'Africa',
              climate: 'Tropical',
              bestTimeToVisit: 'June to October',
              language: 'Swahili, English',
              currency: 'Tanzanian shilling',
              image: '/pictures/africa/tanzania.jpg'
            },
            {
              id: 17,
              name: 'Auckland',
              description: 'The largest city in New Zealand, known for its natural beauty and outdoor activities.',
              continent: 'Oceania',
              climate: 'Oceanic',
              bestTimeToVisit: 'December to February',
              language: 'English, Maori',
              currency: 'New Zealand dollar',
              image: '/pictures/australia/newzealand.jpg'
            },
            {
              id: 18,
              name: 'Sydney',
              description: 'The largest city in Australia, known for its beaches, landmarks, and nightlife.',
              continent: 'Oceania',
              climate: 'Temperate',
              bestTimeToVisit: 'September to November, or March to May',
              language: 'English',
              currency: 'Australian dollar',
              image: '/pictures/australia/sydney.jpg'
            },
            {
              id: 19,
              name: 'Athens',
              description: 'The capital and largest city of Greece, known for its ancient landmarks and Mediterranean climate.',
              continent: 'Europe',
              climate: 'Mediterranean',
              bestTimeToVisit: 'April to June, or September to November',
              language: 'Greek',
              currency: 'Euro',
              image: '/pictures/europe/greece.jpg'
            },
            {
              id: 20,
              name: 'Reykjavik',
              description: 'The capital and largest city of Iceland, known for its geothermal pools, glaciers, and aurora borealis.',
              continent: 'Europe',
              climate: 'Subarctic',
              bestTimeToVisit: 'June to August',
              language: 'Icelandic',
              currency: 'Icelandic króna',
              image: '/pictures/europe/iceland.jpg'
            },
            {
              id: 21,
              name: 'London',
              description: 'The capital and largest city of England, known for its history, culture, and landmarks.',
              continent: 'Europe',
              climate: 'Temperate',
              bestTimeToVisit: 'March to May, or September to November',
              language: 'English',
              currency: 'Pound sterling',
              image: '/pictures/europe/london.jpg'
            },
            {
              id: 22,
              name: 'Milan',
              description: 'A city in northern Italy known for its fashion, art, and architecture.',
              continent: 'Europe',
              climate: 'Humid subtropical',
              bestTimeToVisit: 'April to May, or September to October',
              language: 'Italian',
              currency: 'Euro',
              image: '/pictures/europe/milano.jpg'
            },
            {
              id: 23,
              name: 'Paris',
              description: 'The capital and largest city of France, known for its art, fashion, and landmarks.',
              continent: 'Europe',
              climate: 'Temperate',
              bestTimeToVisit: 'April to June, or September to November',
              language: 'French',
              currency: 'Euro',
              image: '/pictures/europe/paris.jpg'
            },
            {
                        id: 24,
                        name: 'Bucharest',
                        description: 'The capital and largest city of Romania.',
                        continent: 'Europe',
                        climate: 'Temperate',
                        bestTimeToVisit: 'May to September',
                        language: 'Romanian',
                        currency: 'Romanian leu',
                        image: '/pictures/europe/romania.jpg'
                      },
                      {
                        id: 25,
                        name: 'Barcelona',
                        description: 'A city in Spain known for its art, architecture, and beaches.',
                        continent: 'Europe',
                        climate: 'Mediterranean',
                        bestTimeToVisit: 'May to June, or September to November',
                        language: 'Spanish',
                        currency: 'Euro',
                        image: '/pictures/europe/spain.jpg'
                      },
                      {
                        id: 26,
                        name: 'Istanbul',
                        description: 'A city in Turkey known for its history, culture, and location at the crossroads of Europe and Asia.',
                        continent: 'Europe/Asia',
                        climate: 'Mediterranean',
                        bestTimeToVisit: 'April to May, or September to October',
                        language: 'Turkish',
                        currency: 'Turkish lira',
                        image: '/pictures/europe/turkey.jpg'
                      },
                      {
                        id: 27,
                        name: 'Buenos Aires',
                        description: 'The capital and largest city of Argentina, known for its tango, food, and architecture.',
                        continent: 'South America',
                        climate: 'Humid subtropical',
                        bestTimeToVisit: 'September to November, or March to May',
                        language: 'Spanish',
                        currency: 'Argentine peso',
                        image: '/pictures/southamerica/argentina.jpg'
                      },
                      {
                        id: 28,
                        name: 'Rio de Janeiro',
                        description: 'A city in Brazil known for its beaches, Carnival, and music.',
                        continent: 'South America',
                        climate: 'Tropical',
                        bestTimeToVisit: 'June to September',
                        language: 'Portuguese',
                        currency: 'Brazilian real',
                        image: '/pictures/southamerica/brazil.jpg'
                      },
                      {
                        id: 29,
                        name: 'Bogotá',
                        description: 'The capital and largest city of Colombia, known for its history, culture, and nightlife.',
                        continent: 'South America',
                        climate: 'Subtropical highland',
                        bestTimeToVisit: 'December to March, or July to August',
                        language: 'Spanish',
                        currency: 'Colombian peso',
                        image: '/pictures/southamerica/colombia.jpg'
                      },
                      {
                        id: 30,
                        name: 'Mexico City',
                        description: 'The capital and largest city of Mexico, known for its history, culture, and food.',
                        continent: 'North America',
                        climate: 'Subtropical highland',
                        bestTimeToVisit: 'March to May, or September to November',
                        language: 'Spanish',
                        currency: 'Mexican peso',
                        image: '/pictures/southamerica/mexico.jpg'
                      },
                      {
                        id: 31,
                        name: 'San Juan',
                        description: 'The capital and largest city of Puerto Rico, known for its beaches, history, and culture.',
                        continent: 'North America',
                        climate: 'Tropical',
                        bestTimeToVisit: 'December to April',
                        language: 'Spanish, English',
                        currency: 'United States dollar',
                        image: '/pictures/southamerica/puertorico.jpg'
                      },
                      {
                        id: 32,
                        name: 'Honolulu',
                        description: 'The capital and largest city of Hawaii, known for its beaches, surfing, and tropical climate.',
                        continent: 'North America',
                        climate: 'Tropical',
                        bestTimeToVisit: 'April to June, or September to December',
                        language: 'English, Hawaiian',
                        currency: 'United States dollar',
                        image: '/pictures/northamerica/hawaii.jpg'
                      },
                      {id: 33,
    name: 'New York City',
    description: 'The largest city in the United States, known for its skyline, landmarks, and diversity.',
    continent: 'North America',
    climate: 'Humid subtropical',
    bestTimeToVisit: 'April to June, or September to November',
    language: 'English',
    currency: 'United States dollar',
    image: '/pictures/northamerica/newyork.jpg'
  },
  {
    id: 34,
name: 'Vancouver',
    description: 'A coastal city in Canada known for its natural beauty, outdoor activities, and multiculturalism.',
    continent: 'North America',
    climate: 'Oceanic',
    bestTimeToVisit: 'June to September',
    language: 'English, French',
    currency: 'Canadian dollar',
    image: '/pictures/northamerica/canada.jpg'
  },
  {
            id: 35,
            name: 'Miami',
            description: 'A vibrant city in the southeastern United States known for its beaches, nightlife, and Latin American culture.',
            continent: 'North America',
            climate: 'Tropical',
            bestTimeToVisit: 'December to May',
            language: 'English, Spanish',
            currency: 'United States dollar',
            image: '/pictures/northamerica/miami.jpg'
          },
          {
            id: 36,
            name: 'San Francisco',
            description: 'A city in California known for its hilly terrain, iconic Golden Gate Bridge, and cultural diversity.',
            continent: 'North America',
            climate: 'Mediterranean',
            bestTimeToVisit: 'September to November, or March to May',
            language: 'English',
            currency: 'United States dollar',
            image: '/pictures/northamerica/sanfransisco.jpg'
          },
          {
            id: 37,
            name: 'Boston',
            description: 'The capital and largest city of Massachusetts, known for its history, education, and sports.',
            continent: 'North America',
            climate: 'Humid continental',
            bestTimeToVisit: 'May to October',
            language: 'English',
            currency: 'United States dollar',
            image: '/pictures/northamerica/boston.jpg'
          },
          {
            id: 38,
            name: 'Los Angeles',
            description: 'A city in California known for its film industry, beaches, and diverse population.',
            continent: 'North America',
            climate: 'Mediterranean',
            bestTimeToVisit: 'March to May, or September to November',
            language: 'English, Spanish',
            currency: 'United States dollar',
            image: '/pictures/northamerica/losangeles.jpg'
          },
          {
            id: 39,
            name: 'Austin',
            description: 'The capital of Texas, known for its live music, food scene, and outdoor activities.',
            continent: 'North America',
            climate: 'Humid subtropical',
            bestTimeToVisit: 'March to May, or September to November',
            language: 'English, Spanish',
            currency: 'United States dollar',
            image: '/pictures/northamerica/austin.jpg'
          }


]